# Generated by Django 5.1.6 on 2025-03-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=9)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('total_yel_card', models.IntegerField()),
                ('total_red_card', models.IntegerField()),
                ('total_scoring_att', models.IntegerField()),
                ('ontarget_scoring_att', models.IntegerField()),
                ('hit_woodwork', models.IntegerField()),
                ('att_hd_goal', models.IntegerField()),
                ('total_cross', models.IntegerField()),
                ('corner_taken', models.IntegerField()),
                ('touches', models.IntegerField()),
                ('big_chance_missed', models.IntegerField(blank=True, null=True)),
                ('clearance_off_line', models.IntegerField()),
                ('dispossessed', models.IntegerField(blank=True, null=True)),
                ('penalty_save', models.IntegerField()),
                ('total_high_claim', models.IntegerField()),
                ('punches', models.IntegerField()),
            ],
        ),
    ]
